=== llriccardo98ll/DSP_ToDoManagerService/JSON Schemas/task_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://ToDoManager.com/task_schema.json",
    "$title": "Task",
    "description": "JSON Schema for Task objects",
    "type": "object",
    "additionalItems": false,
    "properties": {
        "$schema": {
            "type": "string",
            "description": "path to the JSON Schema to use for the validation of the JSON file describing the task"
        },
        "id": {
            "type": "integer",
            "description": "unique identifier of the task in the ToDo Manager service (mandatory)"
        },
        "description": {
            "type": "string",
            "maxLength": 160,
            "description": "textual description of the task (mandatory, maximum length: 160 characters)"
        },
        "important": {
            "type": "boolean",
            "defaul": false,
            "description": "this Boolean property is set to true if the task is marked as important, false otherwise (default value: false)"
        },
        "private": {
            "type": "boolean",
            "default": true,
            "description": "this Boolean property is set to true if the task is marked as private, false if the task is public (default value: false). \n A task is said private if only the user who created it can get information about it, public if every user can get information about it"
        },
        "projects": {
            "type": "array",
            "description": "the name of the project in which the task is inserted. In the ToDo Manager service, only a predetermined set of the possible values for projects must be accepted (e.g., you can suppose that 'Personal', 'WA1_Project', 'WA2_Project', 'DSP_Project' are th only acceptable values for the projects field)",
            "items": {
                "type": "string",
                "enum": [
                    "Personal",
                    "WA1_Project",
                    "WA2_Project",
                    "DPS_Project"
                ]
            }
        },
        "deadline": {
            "type": "string",
            "pattern": "202[0-9]-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])",
            "description": "the due date and hour of the task. The ToDo Manager service must accept only dates following Junary 1st, 2020. The date format must be compliant to the ISO 8601 standard"
        },
        "completed": {
            "type": "boolean",
            "default": false,
            "description": "this Boolean property is set to true if the task is marked as completed, false otherwise (defaul value: false)"
        },
        "owner": {
            "$ref": "./user_schema.json"
        },
        "assignedTo": {
            "type": "array",
            "items": {
                "$ref": "./user_schema.json"
            }
        }
    },
    "required": [
        "id",
        "description"
    ]
}

=== llriccardo98ll/DSP_ToDoManagerService/JSON Schemas/task_test/task01.json
{
    "$schema": "./../task_schema.json",

    "id": 1,
    "description": "Exam task",
    "important": false,
    "projects": ["Personal", "WA1_Project"],
    "deadline": "2021-12-11T00:00:00Z",
    "completed": false,
    "owner": {
        "id": 1,
        "name": "John",
        "email": "john@polito.it"
    },
    "assignedTo": [
        {
            "id": 1,
            "name": "John",
            "email": "john@polito.it"
        },
        {
            "id": 2,
            "name": "Mary",
            "email": "mary@polito.it"
        }
    ]
}
